### ISSUE TITLE
`QCoreApplication::arguments: Please instantiate the QApplication object first` with Qt 5.7

### ISSUE THREAD

**Issue by missdeer** [sjinks/qt_eventdispatcher_libuv#1]
I just include eventdispatcher_libuv.pri in my .pro file, then build and link successfully, but when I tried to launch the application, it complains `QCoreApplication::arguments: Please instantiate the QApplication object first`

**Comment by sjinks** [comment]
Could you please show the code?

**Comment by missdeer** [comment]
I didn't add any additional code for the purpose, just add the .pri file:

``` cpp
int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    QCoreApplication::setApplicationName("xxx");
    QCoreApplication::setApplicationVersion("1.0");
    ...
    return a.exec();
}
```

No matter I do setEventDispatcher at the beginning of main function or not, it complains `QCoreApplication::arguments: Please instantiate the QApplication object first`

**Comment by sjinks** [comment]
But where do you call `QCoreApplication::arguments`?

**Comment by sjinks** [comment]
Is there any class (say, in the global scope) which could be instantiated before QApplication?

**Comment by missdeer** [comment]
The complete main function:

``` cpp
int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    QCoreApplication::setApplicationName("xxx");
    QCoreApplication::setApplicationVersion("1.0");

    QCommandLineParser parser;
    parser.setApplicationDescription("xxx");
    parser.addHelpOption();
    parser.addVersionOption();

    parser.addOption(QCommandLineOption(QStringList() << "f" << "file", "Save temporary database into local file system."));
    parser.addOption(QCommandLineOption(QStringList() << "t" <<  "temporary-directory", "Save temporary files into <directory>.", "directory"));
    parser.addOption(QCommandLineOption(QStringList() << "s" <<  "source-directory", "Source code stored in <directory>.", "directory"));
    parser.addPositionalArgument("logs", "logs files, zip packages or folders.");
    // Process the actual command line arguments given by the user
    parser.process(a);

    QString t = parser.value("t");
    if (!t.isEmpty())
        g_settings.setTemporaryDirectory( t );

    if (g_settings.temporaryDirectory().isEmpty())
    {
        t = QStandardPaths::writableLocation(QStandardPaths::TempLocation);
        t.append("/CiscoJabberLogs/database");
        g_settings.setTemporaryDirectory( t );
    }

    if (!parser.value("s").isEmpty())
        g_settings.setSourceDirectory( parser.value("s"));

    g_settings.setInMemoryDatabase(!parser.isSet("f"));

    const QStringList logs = parser.positionalArguments();

    MainWindow w;
    w.showMaximized();

    return a.exec();
}
```

Yes, there is a g_settings object that is instantiated before QApplication.

**Comment by sjinks** [comment]
OK, if you comment out

`QCoreApplication::setEventDispatcher(new qtjs::EventDispatcherLibUv);`

does the error still happen?

**Comment by missdeer** [comment]
The error always happens no matter I do setEventDispatcher or not.

**Comment by sjinks** [comment]
Well, but if you do not instantiate the dispatcher, why do you think that the error is related to it?

**Comment by missdeer** [comment]
If I remove the included `qt_eventdispatcher_libuv/lib/eventdispatcher_libuv.pri` file from my .pro file, the application works fine.

**Comment by missdeer** [comment]
BTW, seemly it also hooks command line arguements:

```
QCoreApplication::arguments: Please instantiate the QApplication object first

QCommandLineParser: argument list cannot be empty, it should contain at least the executable name
```

I'm using libuv-0.10.37.

**Comment by sjinks** [comment]
Ah, sorry, I have not noticed you are using LibUV… It is still work in progress and does not pass Qt tests.

**Comment by missdeer** [comment]
Errrr..
